/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'surface-container-lowest': '#0c0e14',
        'surface':                  '#111319',
        'background':               '#111319',
        'surface-container-low':    '#191b22',
        'surface-container':        '#1e1f26',
        'surface-container-high':   '#282a30',
        'surface-container-highest':'#33343b',
        'surface-variant':          '#33343b',
        'on-surface':               '#e2e2eb',
        'on-background':            '#e2e2eb',
        'on-surface-variant':       '#c2c6d5',
        'outline':                  '#8c909e',
        'outline-variant':          '#424753',
        'primary':                  '#acc7ff',
        'primary-container':        '#508ff8',
        'on-primary':               '#002f68',
        'on-primary-container':     '#00285b',
        'secondary':                '#4edea3',
        'secondary-container':      '#00a572',
        'on-secondary':             '#003824',
        'on-secondary-container':   '#00311f',
        'tertiary':                 '#ddb7ff',
        'tertiary-container':       '#b76dff',
        'error':                    '#ffb4ab',
        'error-container':          '#93000a',
        'on-error':                 '#690005',
      },
      fontFamily: {
        sans:     ['Inter', 'system-ui', 'sans-serif'],
        body:     ['Inter', 'system-ui', 'sans-serif'],
        headline: ['Inter', 'system-ui', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        sm:      '0.125rem',
        md:      '0.25rem',
        lg:      '0.25rem',
        xl:      '0.5rem',
        full:    '0.75rem',
      },
    },
  },
  plugins: [],
}
